services:
  api:
    container_name: wasal-api
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/wasal
      - JWT_SECRET=wasal_super_secret_key
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongo

  mongo:
    container_name: wasal-db
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: